# -*- coding: utf-8 -*-
"""control.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13tsblBO_0hREaD1RhmcoI8lRpB7vahTW
"""

# control.py
import pygame

class ControlPanel:
    def __init__(self):
        self.buttons = []
        self.sliders = []
        self.setup_controls()

    def setup_controls(self):
        self.buttons.append(Button(10, 10, 100, 50, "Laminar"))
        self.buttons.append(Button(120, 10, 100, 50, "Turbulent"))

    def handle_events(self, event, simulation):
        for button in self.buttons:
            if button.is_clicked(event):
                if button.text == "Laminar":
                    simulation.switch_mode('laminar')
                elif button.text == "Turbulent":
                    simulation.switch_mode('turbulent')

    def update_controls(self, window):
        for button in self.buttons:
            button.draw(window)

class Button:
    def __init__(self, x, y, width, height, text):
        self.rect = pygame.Rect(x, y, width, height)
        self.text = text

    def draw(self, window):
        pygame.draw.rect(window, (200, 200, 200), self.rect)
        font = pygame.font.Font(None, 36)
        text = font.render(self.text, True, (0, 0, 0))
        window.blit(text, self.rect.topleft)

    def is_clicked(self, event):
        if event.type == pygame.MOUSEBUTTONDOWN:
            if self.rect.collidepoint(event.pos):
                return True
        return False