# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TBeeYXCldhap6-ngeeebDtFWPT1fqjj7
"""

# main.py
import pygame
# from simulation import FluidSimulation
# from visualization import Visualization
# from boundary import Boundary
# from control import ControlPanel

def main():
    width, height = 800, 600
    visualization = Visualization(width, height)
    simulation = FluidSimulation(num_particles=100)
    boundary = Boundary(50, 50, 700, 500)
    control_panel = ControlPanel()

    clock = pygame.time.Clock()
    running = True
    while running:
        dt = clock.tick(60) / 1000.0

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            control_panel.handle_events(event, simulation)

        simulation.update_simulation(dt)
        visualization.draw_particles(simulation.particles)
        visualization.draw_boundaries([boundary])
        control_panel.update_controls(visualization.window)

    pygame.quit()

if __name__ == "__main__":
    main()