# -*- coding: utf-8 -*-
"""visualization.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grMhhmmkX2tcvvYXWxelyr2JwJ9qbt_u
"""

# visualization.py
import pygame

class Visualization:
    def __init__(self, width, height):
        pygame.init()
        self.window = pygame.display.set_mode((width, height))
        self.width = width
        self.height = height

    def draw_particles(self, particles):
        self.window.fill((255, 255, 255))
        for particle in particles:
            pygame.draw.circle(self.window, particle.color, particle.position.astype(int), 3)
        pygame.display.flip()

    def draw_boundaries(self, boundaries):
        for boundary in boundaries:
            pygame.draw.rect(self.window, (0, 0, 0), boundary.rect)